### ISSUE TITLE
Get rid of browser bar

### ISSUE THREAD

**Issue by samuba** [devnews/web#13]
Right now the browser bar is wasting space because it is not necessary and even a hindrance for the  app-like feel that devnews is aiming for.

This could easily be done with the mobile-web-app-capable tag. It will only have effect if the site was started from a shortcut on the homescreen.

**Comment by sunnysingh** [comment]
Good find, and I appreciate you submitting a PR for this. I merged and deployed the change 👍 
Not sure on iOS, but I had to remove and re-add the homescreen shortcut on Android and the URL bar is now hidden.
