### ISSUE TITLE
Github trending tab not loading

### ISSUE THREAD

**Issue by betoharres** [devnews/web#24]
Hello, 
thanks for creating this website. I open it everyday multiple times a day, maybe because I like the design a lot; somehow I got addicted =]
Unfortunately the github trending tab throws an error when it tries to load; I think it's because some breaking change from the github api.
I've tried to fix it by myself last year(I think) but I couldn't get my head around the issue. So now I just have to open github stars in a separate tab :/
Is there any plan to continue with the website? I really hope so!
Thanks

**Comment by sunnysingh** [comment]
Hi @betoharres, thanks for reporting this issue. I do still use this site daily and had some plans for a V2 but other projects got in the way.

There is this alternative GitHub Trending API that could be swapped in: https://github.com/huchenme/github-trending-api

Let me know if you would like to tackle replacing the current API with it. If not I would be happy to take a look when I get more time within the next week.

**Comment by sunnysingh** [comment]
@betoharres I was actually able to implement this change really quickly. The GitHub tab is now working! 🎉 https://devne.ws

**Comment by betoharres** [comment]
@sunnysingh Wow!!! That's awesome! :D haha Many thanks man, I'm so happy it's working again =]] I owe you some beers/coffes! xD
